version: "3.9"

services:
  apps-api:
    build: .
    container_name: apps-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__TestingConnection: ${DB_CONNECTION}
    networks:
      - apps-network

networks:
  apps-network:
    driver: bridge